"""Initial schema

Revision ID: fcf1d9eebba1
Revises:
Create Date: 2026-08-30 10:49:52.183867

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcf1d9eebba1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuracion",
        sa.Column("clave", sa.String(), nullable=False),
        sa.Column("valor", sa.String(), nullable=False),
        sa.Column("es_secreto", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("clave"),
    )
    op.create_table(
        "snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("estado", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_identifier", sa.String(), nullable=False),
        sa.Column("total_chunks", sa.Integer(), nullable=True),
        sa.Column("uploaded_chunks", sa.Integer(), nullable=True),
        sa.Column("size_bytes_raw", sa.Integer(), nullable=True),
        sa.Column("size_bytes_stored", sa.Integer(), nullable=True),
        sa.Column("encrypted_dek", sa.LargeBinary(), nullable=False),
        sa.Column("dek_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("dek_tag", sa.LargeBinary(), nullable=False),
        sa.Column("multipart_upload_id", sa.String(), nullable=True),
        sa.Column("error_detail", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bloques",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.String(), nullable=False),
        sa.Column("chunk_seq", sa.Integer(), nullable=False),
        sa.Column("hash_sha256", sa.String(), nullable=False),
        sa.Column("size_compressed", sa.Integer(), nullable=False),
        sa.Column("size_encrypted", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("etag", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["snapshot_id"], ["snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "chunk_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bloques")
    op.drop_table("snapshots")
    op.drop_table("configuracion")
    # ### end Alembic commands ###
